## 데이터 준비
- https://www.kaggle.com/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows/

In [1]:
import pandas as pd

In [2]:
cols = ['Series_Title', 'Released_Year', 'Meta_score', 'IMDB_Rating', 'Overview']

In [3]:
# 가져올 열 지정하기
movie_df = pd.read_csv('imdb_top_1000.csv', usecols=cols)
movie_df

,Series_Title,Released_Year,IMDB_Rating,Overview,Meta_score
0,The Shawshank Redemption,1994,9.3,Two imprisoned men bond over a number of years...,80.0
1,The Godfather,1972,9.2,An organized crime dynasty's aging patriarch t...,100.0
2,The Dark Knight,2008,9.0,When the menace known as the Joker wreaks havo...,84.0
3,The Godfather: Part II,1974,9.0,The early life and career of Vito Corleone in ...,90.0
4,12 Angry Men,1957,9.0,A jury holdout attempts to prevent a miscarria...,96.0
...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,7.6,A young New York socialite becomes interested ...,76.0
996,Giant,1956,7.6,Sprawling epic covering the life of a Texas ca...,84.0
997,From Here to Eternity,1953,7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0
998,Lifeboat,1944,7.6,Several survivors of a torpedoed merchant ship...,78.0
999,The 39 Steps,1935,7.6,A man in London tries to help a counter-espion...,93.0

## 열 조회

In [5]:
# 단일 열 조회를 하면 Series가 return된다.
movie_df['Series_Title']

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
995      Breakfast at Tiffany's
996                       Giant
997       From Here to Eternity
998                    Lifeboat
999                The 39 Steps
Name: Series_Title, Length: 1000, dtype: object

In [6]:
# 다중 열 조회를 하면 DataFrame
movie_df[['Series_Title','IMDB_Rating']]

                 Series_Title  IMDB_Rating
0    The Shawshank Redemption          9.3
1               The Godfather          9.2
2             The Dark Knight          9.0
3      The Godfather: Part II          9.0
4                12 Angry Men          9.0
..                        ...          ...
995    Breakfast at Tiffany's          7.6
996                     Giant          7.6
997     From Here to Eternity          7.6
998                  Lifeboat          7.6
999              The 39 Steps          7.6

[1000 rows x 2 columns]

In [7]:
# 없는 열을 조회하면 Error
movie_df['AAA']

KeyError: 'AAA'

좀 더 안전하게 가져올 땐, 파이썬 Dictionary처럼 .get()를 이용해보자.

movie_df.get('Series_Title')

In [9]:
movie_df.get(['Series_Title','IMDB_Rating'])

                 Series_Title  IMDB_Rating
0    The Shawshank Redemption          9.3
1               The Godfather          9.2
2             The Dark Knight          9.0
3      The Godfather: Part II          9.0
4                12 Angry Men          9.0
..                        ...          ...
995    Breakfast at Tiffany's          7.6
996                     Giant          7.6
997     From Here to Eternity          7.6
998                  Lifeboat          7.6
999              The 39 Steps          7.6

[1000 rows x 2 columns]

In [11]:
movie_df.get('AAA')

1. 에러 발생을 제어할 건지
2. `.get()`함수로 안전하게 조회할 건지 결정
3. `[ ]` 로 접근하는 건 address access고 .get()조회하는 건 return value(값 반환)이라서
4. 전자는 접근 후 수정이 되고, 후자는 수정이 되지 않는다.

## 열 추가 - 1. 일련화 된 값
- 내가 본 영화를 체크하는 란을 만들자.
- 리스트의 .append()처럼 위치는 지정할 수 없다. (뒤에 붙음)

In [13]:
# 마치 dict형에서 값 추가하듯
movie_df['Watched'] = False

In [14]:
# 확인해 보면
movie_df.head()

,Series_Title,Released_Year,IMDB_Rating,Overview,Meta_score,Watched
0,The Shawshank Redemption,1994,9.3,Two imprisoned men bond over a number of years...,80.0,False
1,The Godfather,1972,9.2,An organized crime dynasty's aging patriarch t...,100.0,False
2,The Dark Knight,2008,9.0,When the menace known as the Joker wreaks havo...,84.0,False
3,The Godfather: Part II,1974,9.0,The early life and career of Vito Corleone in ...,90.0,False
4,12 Angry Men,1957,9.0,A jury holdout attempts to prevent a miscarria...,96.0,False

## 열 추가 - 2. .insert()를 이용한 일련화된 값
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.insert.html
- 나만의 평점을 추가해본다고 하자
- .insert()를 이용하면 위치도 지정할 수 있다.

**loc : int**
Insertion index. Must verify 0 <= loc <= len(columns).

**column :str, number, or hashable object**
Label of the inserted column.

**value : Scalar, Series, or array-like**

**allow_duplicates : bool, optional, default lib.no_default**

- Scalar : 단일 값

In [30]:
# Watched 앞에 넣어보자 ->  추가된 후 최종 위치 -> 0 1 2 3 4 [5] 6위치
movie_df.insert(loc=5, column='My_Score', value= None)

AttributeError: 'NoneType' object has no attribute 'insert'

In [31]:
# 조회
movie_df.head()

AttributeError: 'NoneType' object has no attribute 'head'

## 열 추가 - 3. 다양한 값 추가(Series or array-like)

- value인자 설명을 보면 Series or array-like
- Series와 array-like가 개수만 맞다면 추가 가능

일단은 `My_Score`, `Watched`를 삭제 drop합시다.

In [27]:
# 지난 수업 복습겸 작성해보자.
movie_df.drop(columns=['My_score','Watched'], inplace=True)

AttributeError: 'NoneType' object has no attribute 'head'

### 예시1. Watched를 리스트로 추가해보기

In [44]:
# 예시 watched 생성
watched = [True,False]*500
watched

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

In [45]:
# 처음 배운 [] 방식으로 추가하기
movie_df['Watched'] = watched 
movie_df

TypeError: 'NoneType' object does not support item assignment

### 예시 2. My_Score를 시리즈로 추가해보기

In [35]:
import random
my_score = [random.randint(0, 10) for x in range(1000)]
my_score

[7,
 10,
 8,
 3,
 3,
 4,
 1,
 10,
 8,
 4,
 5,
 8,
 3,
 3,
 1,
 7,
 0,
 5,
 3,
 4,
 1,
 6,
 6,
 3,
 1,
 4,
 10,
 4,
 4,
 4,
 4,
 6,
 2,
 10,
 9,
 9,
 7,
 4,
 2,
 8,
 3,
 2,
 2,
 3,
 3,
 7,
 9,
 7,
 5,
 1,
 6,
 0,
 5,
 5,
 0,
 9,
 0,
 10,
 7,
 2,
 9,
 4,
 7,
 6,
 9,
 4,
 2,
 7,
 4,
 3,
 3,
 4,
 2,
 5,
 0,
 5,
 9,
 9,
 7,
 7,
 6,
 7,
 2,
 10,
 8,
 3,
 10,
 9,
 5,
 1,
 1,
 2,
 7,
 8,
 6,
 8,
 0,
 3,
 9,
 4,
 8,
 5,
 9,
 3,
 2,
 6,
 10,
 2,
 8,
 3,
 9,
 8,
 9,
 4,
 8,
 7,
 7,
 5,
 8,
 1,
 9,
 5,
 7,
 5,
 0,
 6,
 3,
 4,
 3,
 8,
 2,
 3,
 5,
 9,
 8,
 5,
 2,
 3,
 8,
 1,
 2,
 8,
 6,
 8,
 2,
 5,
 5,
 0,
 3,
 5,
 9,
 10,
 2,
 7,
 1,
 4,
 7,
 8,
 9,
 5,
 7,
 10,
 6,
 4,
 9,
 5,
 1,
 5,
 6,
 0,
 2,
 0,
 0,
 8,
 9,
 9,
 9,
 10,
 9,
 3,
 2,
 8,
 1,
 10,
 9,
 0,
 1,
 2,
 2,
 0,
 9,
 8,
 7,
 1,
 10,
 5,
 1,
 7,
 5,
 10,
 9,
 5,
 6,
 2,
 8,
 7,
 4,
 5,
 2,
 4,
 9,
 4,
 8,
 7,
 7,
 8,
 10,
 0,
 3,
 8,
 6,
 5,
 10,
 10,
 8,
 0,
 4,
 2,
 7,
 3,
 3,
 8,
 3,
 2,
 1,
 2,
 2,
 1,
 9,
 9,
 10,
 8,
 1,
 4,
 0,
 10,
 3,
 4,
 9,
 5,
 4,
 3,
 0,
 4,
 8,
 6,
 6,
 6,
 4,
 7,
 6,
 8,
 6,
 9,
 8,
 1,
 3,
 3,
 0,
 9,
 8,
 3,
 2,
 8,
 0,
 10,
 0,
 6,
 6,
 2,
 2,
 10,
 0,
 9,
 0,
 7,
 6,
 6,
 8,
 2,
 6,
 6,
 6,
 3,
 4,
 4,
 7,
 6,
 6,
 8,
 2,
 9,
 1,
 10,
 5,
 9,
 6,
 3,
 3,
 5,
 4,
 10,
 9,
 0,
 7,
 8,
 3,
 0,
 0,
 2,
 3,
 8,
 5,
 6,
 5,
 0,
 9,
 8,
 1,
 4,
 1,
 5,
 2,
 2,
 7,
 1,
 3,
 10,
 7,
 1,
 8,
 7,
 2,
 6,
 3,
 8,
 0,
 10,
 3,
 7,
 2,
 2,
 7,
 9,
 9,
 5,
 0,
 3,
 6,
 8,
 6,
 10,
 2,
 5,
 6,
 4,
 7,
 4,
 1,
 5,
 6,
 2,
 9,
 7,
 7,
 4,
 10,
 7,
 5,
 4,
 8,
 2,
 6,
 0,
 4,
 5,
 3,
 10,
 6,
 7,
 2,
 8,
 10,
 2,
 1,
 7,
 9,
 9,
 6,
 7,
 8,
 4,
 0,
 2,
 5,
 7,
 5,
 10,
 6,
 6,
 0,
 0,
 6,
 6,
 3,
 4,
 5,
 8,
 9,
 5,
 1,
 2,
 10,
 5,
 8,
 5,
 5,
 3,
 6,
 8,
 4,
 5,
 6,
 0,
 1,
 0,
 9,
 1,
 4,
 1,
 1,
 4,
 10,
 6,
 7,
 1,
 3,
 5,
 4,
 4,
 6,
 8,
 9,
 10,
 9,
 3,
 7,
 7,
 9,
 4,
 1,
 1,
 8,
 4,
 9,
 0,
 5,
 4,
 6,
 4,
 0,
 2,
 9,
 6,
 7,
 1,
 6,
 2,
 9,
 7,
 0,
 10,
 1,
 2,
 1,
 7,
 3,
 5,
 2,
 7,
 7,
 6,
 2,
 8,
 3,
 9,
 7,
 8,
 2,
 1,
 3,
 8,
 1,
 0,
 5,
 8,
 10,
 1,
 6,
 5,
 6,
 2,
 1,
 9,
 10,
 8,
 8,
 6,
 0,
 8,
 3,
 6,
 4,
 7,
 7,
 10,
 5,
 2,
 1,
 4,
 7,
 4,
 1,
 8,
 6,
 5,
 5,
 6,
 7,
 7,
 10,
 0,
 10,
 10,
 10,
 7,
 4,
 5,
 0,
 9,
 8,
 2,
 0,
 7,
 7,
 10,
 6,
 7,
 8,
 8,
 6,
 8,
 4,
 8,
 7,
 6,
 1,
 10,
 9,
 0,
 8,
 2,
 7,
 5,
 10,
 5,
 5,
 5,
 10,
 6,
 0,
 0,
 8,
 0,
 10,
 7,
 8,
 5,
 2,
 2,
 2,
 3,
 6,
 7,
 2,
 7,
 2,
 10,
 8,
 0,
 6,
 4,
 3,
 7,
 0,
 5,
 3,
 5,
 8,
 4,
 1,
 3,
 3,
 5,
 10,
 7,
 9,
 2,
 2,
 9,
 1,
 0,
 0,
 0,
 3,
 4,
 4,
 8,
 6,
 1,
 9,
 9,
 1,
 4,
 10,
 8,
 3,
 4,
 2,
 5,
 4,
 3,
 5,
 9,
 4,
 5,
 4,
 0,
 3,
 2,
 8,
 3,
 2,
 1,
 10,
 5,
 4,
 9,
 1,
 8,
 10,
 10,
 5,
 1,
 10,
 4,
 3,
 4,
 7,
 2,
 1,
 10,
 1,
 10,
 0,
 2,
 2,
 3,
 9,
 8,
 7,
 7,
 5,
 1,
 7,
 2,
 3,
 6,
 8,
 7,
 9,
 10,
 9,
 4,
 5,
 3,
 1,
 8,
 2,
 3,
 5,
 3,
 5,
 2,
 7,
 2,
 2,
 2,
 5,
 0,
 10,
 2,
 6,
 10,
 10,
 3,
 4,
 3,
 5,
 10,
 6,
 9,
 1,
 10,
 1,
 8,
 3,
 3,
 1,
 9,
 5,
 3,
 5,
 9,
 10,
 9,
 9,
 8,
 4,
 3,
 8,
 6,
 0,
 3,
 2,
 2,
 2,
 0,
 5,
 4,
 3,
 7,
 4,
 8,
 1,
 7,
 3,
 9,
 3,
 4,
 3,
 9,
 9,
 5,
 5,
 10,
 7,
 2,
 2,
 7,
 10,
 9,
 7,
 0,
 4,
 6,
 5,
 4,
 1,
 10,
 4,
 6,
 9,
 0,
 10,
 7,
 5,
 0,
 9,
 1,
 0,
 8,
 0,
 4,
 5,
 3,
 9,
 3,
 7,
 0,
 8,
 2,
 10,
 9,
 5,
 4,
 7,
 10,
 0,
 10,
 9,
 10,
 2,
 10,
 0,
 10,
 4,
 2,
 5,
 9,
 1,
 2,
 5,
 2,
 2,
 5,
 3,
 0,
 3,
 9,
 3,
 0,
 0,
 9,
 10,
 1,
 4,
 1,
 2,
 5,
 0,
 4,
 2,
 10,
 0,
 1,
 4,
 10,
 5,
 4,
 6,
 5,
 7,
 7,
 4,
 5,
 7,
 1,
 3,
 10,
 2,
 0,
 5,
 0,
 9,
 6,
 0,
 6,
 3,
 4,
 9,
 7,
 0,
 1,
 10,
 3,
 3,
 2,
 10,
 6,
 6,
 1,
 7,
 10,
 6,
 3,
 0,
 8,
 8,
 10,
 9,
 9,
 10,
 2,
 2,
 2,
 4,
 10,
 1,
 0,
 9,
 3,
 3,
 1,
 10,
 5,
 1,
 10,
 4,
 1,
 4,
 5,
 3,
 5,
 0,
 5,
 0,
 8,
 6,
 4,
 1,
 1,
 1,
 7,
 1,
 7,
 6,
 0,
 3,
 10,
 9,
 4,
 1,
 1,
 4,
 9,
 4,
 1,
 6,
 3,
 4,
 5,
 6,
 2,
 6,
 1,
 2,
 6,
 4,
 10,
 6,
 7,
 6,
 1,
 8,
 1,
 4,
 8,
 9,
 9,
 6,
 7,
 7,
 8,
 1,
 9,
 0,
 4,
 8,
 1,
 6,
 7,
 5,
 5,
 6,
 3,
 5,
 4,
 9,
 8,
 2,
 6,
 8,
 9,
 1,
 2,
 0,
 9,
 6,
 5,
 10,
 9,
 5,
 0,
 1,
 2,
 5,
 0,
 5,
 7]

In [38]:
# 시리즈 생성
my_score_series = pd.Series(my_score)
my_score_series

0       7
1      10
2       8
3       3
4       3
       ..
995     2
996     5
997     0
998     5
999     7
Length: 1000, dtype: int64

In [40]:
# IMDB_Rating 앞에 추가해보자.
movie_df.insert(loc=2, column='My_score', value=my_score_series)

AttributeError: 'NoneType' object has no attribute 'insert'

In [ ]:
# 확인
movie_df

## 만일 데이터의 개수가 안 맞는다면?

### 테스트 1 : [] + `array-like` 로 열 추가 방식

In [46]:
watched

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

In [47]:
del watched[0]

In [48]:
len(watched)

999

In [50]:
# 테스트 1000개 <-999개  : 에러발생
movie_df['new_Watched'] = watched

TypeError: 'NoneType' object does not support item assignment

ValueError: Length of values (999) does not match length of index (1000)

### 테스트 2 : insert+`Series`로 열 추가 방식

In [51]:
del my_score_series[0]
my_score_series.size

999

In [52]:
# 테스트 1000개 <-999개  : 에러 발생?
movie_df.insert(loc=2, column = 'New_My_Score', value=my_score_seriea)

AttributeError: 'NoneType' object has no attribute 'insert'

In [53]:
movie_df

1. 일치된 인덱스에 맞춰 값이 추가된다.
2. 일치되지 않은 행은 NaN으로 대체된다.

데이터 전처리를 열심히 하다보면 이렇게 NaN데이터가 쉽게 생겨나기도 한다.

### 테스트 3. [] + `Series` 추가하면?

In [56]:
movie_df['new_new_Watched'] = my_score_series

TypeError: 'NoneType' object does not support item assignment

In [55]:
movie_df